package com.community.shetuanbao.utils;

public class Constant {
	
	
	public static String userToken="";
	public static String userName="";//ID
	public static String userPassword="";
	public static Boolean Static=false;
	
	
	
	public static String INSERTFRIEND="<#INSERTFRIEND#>";
	public static String SEARCH="<#SEARCH#>";
	public static String GETFRIEND="<#GETFRIEND#>";
	public static String GETSHETUANRENYUANID="<#GETSHETUANRENYUANID#>";
	public static String GETSHETUANUSERINFO="<#GETSHETUANUSERINFO#>";
	
	public static String GETUSERPEN="<#GETUSERPEN#>";
	
	public static String GetUserName="<#GetUserName#>";
	public static String GetUserFriendName="<#GetUserFriendName#>";
	public static String GetUserFriendPen="<#GetUserFriendPen#>";
	public static String GetOnePicture="<#GetOnePicture#>";
	public static String GetUserFriendPhoto="<#GetUserFriendPhoto#>";
	public static String GetUserFriend="<#GetUserFriend#>";
	public static String GetUserFriendId="<#GetUserFriendId#>";
	public static String GetUserJoinTeam="<#GetUserJoinTeam#>";
	public static String GetUserOnePhoto="<#GetUserOnePhoto#>";
	public static String LOGIN="<#LOGIN#>";
	public static String REGISTER="<#REGISTER#>";
	public static String GetToken="<#GetToken#>";
	public static String GETUSERID="<#GETUSERID#>";
	public static String getshetuanchengyuan="<#getshetuanchengyuan#>";
	
	
	
	public static final String More_getuserId="<#More_getuserId#>";
	public static final String Getuserpassword="<#Getuserpassword#>";
	public static final String Getuserstates = "<#Getuserstates#>";
	public static final String Getandroidactivity="<#Getandroidactivity#>";
	public static final String Getallrecommend="<#Getallrecommend#>";
	public static final String Insertuser="<#Insertuser#>";
	public static final String GetUserPhoto="<#GetUserPhoto#>";
	public static final String Getandroidflashpic="<#Getandroidflashpic#>";
	public static final String Getallrecollect="<#Getallrecollect#>";
	public static final String Getandall="<#Getandall#>";
	public static final String Getandxican="<#Getandxican#>";
	public static final String Getandhuoguo="<#Getandhuoguo#>";
	public static final String Getandzizhu="<#Getandzizhu#>";
	public static final String Getandkuaican="<#Getandkuaican#>";
	public static final String Getandxiaochi="<#Getandxiaochi#>";
	public static final String Getandkafei="<#Getandkafei#>";
	public static final String Getandjiuba="<#Getandjiuba#>";
	public static final String GetSearchName="<#GetSearchName#>";
	public static final String GetSearchName1="<#GetSearchName1#>";
	public static final String Getandactivity_state="<#Getandactivity_state#>";
	public static final String Getactivitylist="<#Getactivitylist#>";
	public static final String Getandactivity="<#Getandactivity#>";
	public static final String Getactivitylistname="<#Getactivitylistname#>";
	public static final String Getuserlist="<#Getuserlist#>";
	public static final String Getusermessagebyid="<#Getusermessagebyid#>";
	public static final String Setusermessagebyid="<#Setusermessagebyid#>";
	public static final String Getonerestaurant="<#Getonerestaurant#>";
	public static final String Setcollect="<#Setcollect#>";
	public static final String Getcollect="<#Getcollect#>";
	public static final String Getcollectname="<#Getcollectname#>";
	public static final String Isexsistcollect="<#Isexsistcollect#>";
	public static final String Deletecollect="<#Deletecollect#>";
	public static final String Sethistory="<#Sethistory#>";
	public static final String Isexsisthistory="<#Isexsisthistory#>";
	public static final String Gethistory="<#Gethistory#>";
	public static final String Deletehistory="<#Deletehistory#>";
	public static final String Getfooddetial="<#Getfooddetial#>";
	public static final String GetComment="<#GetComment#>";
	public static final String Insertcomment="<#Insertcomment#>";
	public static final String Getotherfood="<#Getotherfood#>";
	public static final String Getrescount="<#Getrescount#>";
	public static final String Getandbyarea="<#Getandbyarea#>";
	public static final String Getandresbymenu="<#Getandresbymenu#>";
	public static final String Getandresbysousuo="<#Getandresbysousuo#>";
	public static final String Getrestaurant_food="<#Getrestaurant_food#>";
	public static final String Getrestaurantbyfoodname="<#Getrestaurant_food#>";
	public static final String Feedback="<#Feedback#>";
	public static final String Updateandusermessage="<#Updateandusermessage#>";
	public static final String Getpasswordandphone="<#Getpasswordandphone#>";
	public static final String GetAreaname = "<#GetAreaname#>";//鑾峰緱spinner涓殑鍖哄煙鍚嶇О
	public static final String GetFoodtype = "<#GetFoodtype#>";//鑾峰緱spinner涓殑鑿滅郴绉嶇被
	public static final String Getselectstyle = "<#Getselectstyle#>";//寰楀埌spinner閫夋嫨鐨勬帓搴忔柟寮�
	//public static final String GetAllShetuan="<#GetAllShetuan#>";
    //public static final String GetAllShetuanId="<#GetAllShetuanId#>";
    //public static final String GetShetuanDetail="<#GetShetuanDetail#>";
    //public static final String GetShetuanPeople="<#GetShetuanPeople#>";
	public static final String gethuodongbyname="<#gethuodongbyname#>";//4
	public static final String getshetuanbyname="<#getshetuanbyname#>";//5
	public static final String getshetuanidbyname="<#getshetuanidbyname#>";//6

	public static final String GetAllHuodong="<#GetAllHuodong#>";
	public static final String GetAllHuodongId="<#GetAllHuodongId#>";
    public static final String GetAllHuodongTime="<#GetAllHuodongTime#>";
    public static final String GetAllHuodongPlace="<#GetAllHuodongPlace#>";
    public static final String GetAllHuodngDetail="<#GetAllHuodongDetail#>";
    public static final String GET_Picture="<#GET_Picture#>";
    public static final String GET_SCPicture="<#GET_SCPicture#>";
    public static final String GetOneHuodongTime="<#GetOneHuodongTime#>";
    public static final String GetOneHuodongPlace="<#GetOneHuodongPlace#>";
    public static final String GetAllHuodongPicture="<#GetAllHuodongPicture#>";
    public static final String GetAllHuadongPicture="<#GetAllHuadongPicture#>";
    public static final String GetHuodongName="<#GetHuodongName#>";
    public static final String GetOneHuodongByName="<#GetOneHuodongByName#>";
    public static final String GetOneHuodongTimeByName="<#GetOneHuodongTimeByName#>";
    public static final String GetOneHuodongPlaceByName="<#GetOneHuodongPlaceByName#>";
    public static final String GetOneHuodongIdByName="<#GetOneHuodongIdByName#>";
    public static final String GetOneHuodongPictureByName="<#GetOneHuodongPictureByName#>";
    public static final String GetHuodongPinglun="<#GetHuodongPinglun#>";
    public static final String InsertHuodongPinglun="<#InsertHuodongPinglun#>";
    public static final String GetAllShetuan="<#GetAllShetuan#>";
    public static final String GetAllShetuanId="<#GetAllShetuanId#>";
    public static final String GetShetuanDetail="<#GetShetuanDetail#>";
    public static final String GetShetuanPeople="<#GetShetuanPeople#>";
    public static final String GetTiyuShetuan="<#GetTiyuShetuan#>";
	public static final String GetTiyuShetuanId="<#GetTiyuShetuanId#>";
	public static final String GetWenyiShetuanId="<#GetWenyiShetuanId#>";
	public static final String GetWenyiShetuan="<#GetWenyiShetuan#>";
	public static final String GetCishanShetuan="<#GetCishanShetuan#>";
	public static final String GetCishanShetuanId="<#GetCishanShetuanId#>";
	public static final String GetXueshuShetuan="<#GetXueshuShetuan#>";
	public static final String GetXueshuShetuanId="<#GetXueshuShetuanId#>";
	public static final String GetShetuanKouhao="<#GetShetuanKouhao#>";
	public static final String GetAllShetuanPicture="<#GetAllShetuanPicture#>";
	public static final String GetOneShetuanPicture="<#GetOneShetuanPicture#>";
	public static final String GetShetuanxiangce="<#GetShetuanxiangce#>";
	public static final String GetShetuantiyupicture="<#GetShetuantiyupicture#>";
	public static final String GetShetuantiyukouhao="<#GetShetuantiyukouhao#>";
	public static final String GetShetuantiyupicture2="<#GetShetuantiyupicture2#>";
	public static final String GetShetuanXueshupicture="<#GetShetuanXueshupicture#>";
	public static final String GetShetuanXueshupciture2="<#GetShetuanXueshupciture2#>";
	public static final String GetShetuanXueshukouhao="<#GetShetuanXueshukouhao#>";
	public static final String GetShetuanCishanpicture="<#GetShetuanCishanpicture#>";
	public static final String GetShetuanCishanpicture2="<#GetShetuanCishanpicture2#>";
	public static final String GetShetuanCishankouhao="<#GetShetuanCishankouhao#>";
	public static final String GetShetuanByName="<#GetShetuanByName#>";
	public static final String GetShetuanIdByName="<#GetShetuanIdByName#>";
	public static final String GetShetuanKouhaoByName="<#GetShetuanKouhaoByName#>";
	public static final String GetShetuanPictureByName="<#GetShetuanPictureByName#>";
	public static final String GetShetuanPicture2ByName="<#GetShetuanPicture2ByName#>";
	public static final String GetHuodongPinglunPicture="<#GetHuodongPinglunPicture#>";
    public static final String GetHuodongPinglunName="<#GetHuodongPinglunName#>";
    public static final String GetHuodongPinglunId="<#GetHuodongPinglunId#>";
    public static final String DeleteHuodongPinglun="<#DeleteHuodongPinglun#>";
	public static final String GetShetuanMessage="<#GetShetuanMessage#>";
	public static final String GetAllHuodongMessage="<#GetAllHuodongMessage#>";
	public static final String GetShetuanWenyikouhao="<#GetShetuanWenyikouhao#>";
	public static final String GetShetuanWenyipicture="<#GetShetuanWenyipicture#>";
	public static final String GetShetuanWenyipicture2="<#GetShetuanWenyipicture2#>";
	public static final String InsertPic="<#InsertPic#>";
	public static final String GetHuodongFenbu="<#GetHuodongFenbu#>";
	public static final String GetHuodongMessageByName="<#GetHuodongMessageByName#>";
	public static final String InsertHuodongMessage="<#InsertHuodongMessage#>";
	public static final String GetHuodongPinglunTime="<#GetHuodongPinglunTime#>";
	public static final String GetShetuanDetailPicture="<#GetShetuanDetailPicture#>";
	public static final String GetYiJian="<#GetYiJian#>";
	public static final String getguanliid="<#getguanliid#>";
	public static final String tianjiachenghyuan="<#tianjiachenghyuan#>";
	public static final String shanchuchengyuan="<#shanchuchengyuan#>";
	public static final String getallshetuanchengyuan="<#getallshetuanchengyuan#>";
	public static final String getshetuan="<#getshetuan#>";
	public static final String getallguanlihuodong="<#getallguanlihuodong#>";
	public static final String getmaxid="<#getmaxid#>";
	public static final String getcommunityid="<#getcommunityid#>";
	public static final String inserthuodongm="<#inserthuodongm#>";
	public static final String getguanliyuankouling="<#getguanliyuankouling#>";
	public static final String deletehuodong="<#deletehuodong#>";
	public static String GetXiangceById = "<#GetXiangceById#>";
	public static String deletexiangce="<#deletexiangce#>";
	public static String insertxiangce="<#insertxiangce#>";
	public static String updataxiangce="<#updataxiangce#>";
	public static String getid="<#getid#>";
	public static String getallguanlihuodongid="<#getallguanlihuodongid#>";
	public static String gethuseridbyname="<#gethuseridbyname#>";
	public static String getshetuantohuodong="<#getshetuantohuodong#>";
	public static final String GET_USERNAME_AND_PICTURE="<#GET_USERNAME_AND_PICTURE#>";
	public static final String GET_HUODONG_XIANGCE="<#GET_HUODONG_XIANGCE#>";
	
	public static String getallchengyuan="<#getallchengyuan#>";
	public static String shanchuhaoyou="<#shanchuhaoyou#>";
	public static String GET_ALLUSERID="<#GET_ALLUSERID#>";
	public static String GET_USERPICTURE="<#GET_USERPICTURE#>";
	public static String GET_USERNAMEBUID="<#GET_USERNAMEBUID#>";
	public static String GET_USERSTATIC="<#GET_USERSTATIC#>";
	public static String GET_SHETUANIDBYMIMA="<#GET_SHETUANIDBYMIMA#>";
	public static String GET_CUNZAISHETUANCHENGYUAN="<#GET_CUNZAISHETUANCHENGYUAN#>";
	public static String GET_SHANCHUSHETUANCHENGYUAN="<#GET_SHANCHUSHETUANCHENGYUAN#>";
	public static String GET_TIANJIACUNZAICHENGYUAN="<#GET_TIANJIACUNZAICHENGYUAN#>";
	public static String GET_USERNAME="<#GET_USERNAME#>";
	public static final String GET_HUODONGRENYUANXINGMING="<#GET_HUODONGRENYUANXINGMING#>";
	public static final String GET_HUODONGRENYUANID="<#GET_HUODONGRENYUANID#>";
	public static final String GET_USERZHUANYE="<#GET_USERZHUANYE#>";
	public static final String GET_XUEYUAN="<#GET_XUEYUAN#>";
	public static final String GET_USERSEX="<#GET_USERSEX#>";
	public static final String GET_SUERSHETUAN="<#GET_SUERSHETUAN#>";
	public static final String PD_SHETUANRENYUAN="<#PD_SHETUANRENYUAN#>";
	public static final String INSERT_HUODONGRENYUAN="<#INSERT_HUODONGRENYUAN#>";
	public static final String SHIFOUBAOMING="<#SHIFOUBAOMING#>";
	public static final String GET_HUODONGLEIXING="<#GET_HUODONGLEIXING#>";
	public static final String GET_SHETUANRENZT="<#GET_SHETUANRENZT#>";
}
